/*
* This code has been generated by the Rebel: a code generator for modern Java.
* 
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/

package com.airport.mgmt.controllers;

import com.airport.mgmt.resources.GateAvailabilityResource;
import com.airport.mgmt.services.GateService;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.bind.annotation.*;

import java.time.LocalTime;


@Transactional
@RestController
@RequestMapping("/gates")
public class GateController {
    private static final Logger logger = LoggerFactory.getLogger(GateController.class);

    private final GateService service;

    @Autowired
    public GateController(GateService service) {
        this.service = service;
    }

    @PostMapping("makeAvailable")
    @ResponseStatus(HttpStatus.OK)
    public void makeGateAvailable(@RequestParam String gateName){
        service.makeGateAvailable(gateName);
    }

    @PostMapping("updateAvailability")
    @ResponseStatus(HttpStatus.OK)
    public void updateGateTimeAvailability(@RequestBody GateAvailabilityResource resource){
        service.updateGateTimeAvailability(resource.getGateName(), resource.getAvailableFrom(), resource.getAvailableTo());
    }
}