/*
* This code has been generated by the Rebel: a code generator for modern Java.
* 
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/

package com.airport.mgmt.controllers;

import com.airport.mgmt.resources.GateAvailabilityResource;
import com.airport.mgmt.services.GateService;
import lombok.extern.slf4j.Slf4j;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.bind.annotation.*;

@Slf4j
@Transactional
@RestController
@RequestMapping("/gates")
public class GateController {
    private final GateService service;

    @Autowired
    public GateController(GateService service) {
        this.service = service;
    }

    @PostMapping("makeAvailable")
    @ResponseStatus(HttpStatus.NO_CONTENT)
    public void makeGateAvailable(@RequestParam String gateName){
        service.makeGateAvailable(gateName);
        log.info("Gate {} is now available", gateName);

    }

    @PostMapping("updateAvailability")
    @ResponseStatus(HttpStatus.NO_CONTENT)
    public void updateGateTimeAvailability(@RequestBody GateAvailabilityResource resource){
        service.updateGateTimeAvailability(resource.getGateName(), resource.getAvailableFrom(), resource.getAvailableTo());
        log.info("Gate time availability is updated. Gate {} is now available from {} to {}", resource.getGateName(), resource.getAvailableFrom(), resource.getAvailableTo());
    }
}