/*
* This code has been generated by the Rebel: a code generator for modern Java.
* 
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package com.airport.mgmt.domain;

import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.util.*;
import java.time.*;

import javax.persistence.*;
import javax.validation.constraints.*;


// ----------- << imports@AAAAAAF2pMmOZc4XaLY= >>
// ----------- >>

@Entity
@Getter
@Setter
@NoArgsConstructor
// ----------- << class.annotations@AAAAAAF2pMmOZc4XaLY= >>
// ----------- >>
public class Account {
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    // ----------- << id.annotations@AAAAAAF2pMmOZc4XaLY= >>
    // ----------- >>
    private Long id;

    @Version
    // ----------- << version.annotations@AAAAAAF2pMmOZc4XaLY= >>
    // ----------- >>
    private Long version;

    @NotNull
    @Column(nullable = false)
    // ----------- << attribute.annotations@AAAAAAF2pMsNgs9CEv8= >>
    // ----------- >>
    private String firstName;

    @NotNull
    @Column(nullable = false)
    // ----------- << attribute.annotations@AAAAAAF2pMtigc9/Gpo= >>
    // ----------- >>
    private String lastName;

    @ElementCollection
    // ----------- << attribute.annotations@AAAAAAF2pMy3zNAYB28= >>
    // ----------- >>
    private Set<Role> roles = new HashSet<>();

    // ----------- << getId.annotations@AAAAAAF2pMmOZc4XaLY= >>
    // ----------- >>
    public Long getId(){
        return id;
    }

    // ----------- << equals.annotations@AAAAAAF2pMmOZc4XaLY= >>
    // ----------- >>
    @Override
    public boolean equals(Object obj) {
        if (super.equals(obj)) return true;
        if (getId() == null) return false;
        return obj instanceof Account && (getId().equals(((Account) obj).getId()));
    }

    // ----------- << hashCode.annotations@AAAAAAF2pMmOZc4XaLY= >>
    // ----------- >>
    @Override
    public int hashCode() {
        return 251;
    }

// ----------- << class.extras@AAAAAAF2pMmOZc4XaLY= >>
// ----------- >>
}