/*
* This code has been generated by the Rebel: a code generator for modern Java.
* 
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package com.airport.mgmt.domain;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF2pLkSX8nkVds= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF2pLkSX8nkVds= >>
// ----------- >>
public enum Role {
    administrator,
    other;

// ----------- << enum.extras@AAAAAAF2pLkSX8nkVds= >>
// ----------- >>
}